---
title: "Life Policy Generation: 11 - Create Life Policy Lapses"
author: "Mick Cooney"
date: "1 October 2016"
output:
  html_document:
    toc: true
    number_sections: true
    fig_caption: yes
    theme: cerulean
    css: assets/styles.css
  pdf_document: default
---

<!--
(Title:) Life Policy Generation: 11 - Create Life Policy Lapses

Author: Mick Cooney

Date: 2016

Abstract: This worksheet adds lapse information to the book of life policies.

Keywords: life insurance, insurance, data generation

-->




This worksheet enables the generation of a fake book of policies for a life insurance company in Ireland


```{r knit_opts, echo=FALSE}
knitr::opts_chunk$set(tidy = FALSE, cache = FALSE)

library(tidyverse)
library(data.table)
library(dtplyr)

library(feather)

library(lubridate)

source("custom_functions.R")

set.seed(4211)
```

## Load Input Data

### Set up input parameters

```{r create_input_parameters, echo=TRUE}
data_date <- as.Date('2015-12-31')

min_monthly_lapse_prob <- 0.0001

premape_high <- 5000

nonprotection_weibull_shape <- 10
nonprotection_weibull_scale <- 100
```

### Load Data from Files

```{r load_policy_data, echo=TRUE}
dt_policy <- readRDS("output/lifeins_policybook.rds")

str(dt_policy)
```

# Create Additive Lapse Probabilities

```{r create_inputs_basic, echo=TRUE}
max_length   <- dt_policy[, max(policy_duration, na.rm = TRUE)]
total_months <- 12 * max_length

### Create the baseline hazard rate
baseline_prob          <- 0.0070
baseline_higher_prob   <- 0.0085
baseline_higher_months <- 12

risk_baseline                           <- rep(baseline_prob, total_months)
risk_baseline[1:baseline_higher_months] <- baseline_higher_prob
```

```{r create_inputs_demographics, echo=TRUE}
# We will use the following parameters to affect the hazard rate
#
# gender_life1:    Male policy holders will lapse more, but this will decrease over time
# smoker_life1:    This will affect the hazard rate for the first three years but then will switch and decrease it
# mortgage_status: MORTFULL and MORTDECR will decrease the lapse rate for the first 3 years, go flat till about 7 years,
#                  and then increase it
# log(prem_ape):   This will be high at the start and slowly decay to zero, probably exponentially
# cluster_id:      This will have a few different effects for a couple of clusters, but most will have no effect.
# iflifeonly:      This will increase lapses by a small amount as a constant rate if FALSE
# policy_duration: This will slightly increase the lapse rate if the mortgage is for over 10 years

gender_prob <- 0.0020

risk_gender        <- rep(0, total_months)
risk_gender[1:24]  <- gender_prob
risk_gender[25:36] <- 0.5 * gender_prob


### Create the smoker hazard rate
smoker_prob_initial <-  0.0010
smoker_prob_later   <- -0.0005
smoker_prob_quitter <-  0.0020

risk_smoker <- list("N" = rep(0, total_months)
                   ,"S" = rep(0, total_months)
                   ,"Q" = rep(0, total_months))

risk_smoker[["S"]][1:36]            <- smoker_prob_initial
risk_smoker[["S"]][49:total_months] <- smoker_prob_later

risk_smoker[["Q"]][37:total_months] <- smoker_prob_quitter


### Create the mortgage_status hazard rate

mortstat_prob_initial <- -0.0005
mortstat_prob_later   <- +0.0010

risk_mortstat <- list('MORTDECR' = rep(0, total_months)
                     ,'MORTFULL' = rep(0, total_months)
                     ,'TERM'     = rep(0, total_months))

risk_mortstat[['MORTDECR']][1:36]            <- mortstat_prob_initial
risk_mortstat[['MORTDECR']][61:total_months] <- mortstat_prob_later

risk_mortstat[['MORTFULL']][1:36]            <- mortstat_prob_initial
risk_mortstat[['MORTFULL']][61:total_months] <- 0.5 * mortstat_prob_later
```



```{r create_inputs_premium, echo=TRUE}
### Create the prem_ape hazard rate

### For now I'll just go with a fairly straightforward dependency on
### prem_ape, where it multiplies the log(prem_ape)

logpremape_mult_start  <- 2e-5
logpremape_mult_finish <- 1e-5

risk_logpremape <- rep(0, total_months)

risk_logpremape[1:24]            <- logpremape_mult_start
risk_logpremape[48:total_months] <- logpremape_mult_finish

high_premape_start <-  0.0050
high_premape_end   <- -0.0030

risk_highpremape <- rep(0, total_months)

risk_highpremape[1:12]            <- high_premape_start
risk_highpremape[37:total_months] <- high_premape_end


### Create the cluster_id hazard rate
c4_prob         <- -0.0010
c5_prob_initial <-  0.0050
c5_prob_later   <-  0.0020

risk_cluster <- list("n6_c0" = rep(0, total_months)
                    ,"n6_c1" = rep(0, total_months)
                    ,"n6_c2" = rep(0, total_months)
                    ,"n6_c3" = rep(0, total_months)
                    ,"n6_c4" = rep(0, total_months)
                    ,"n6_c5" = rep(0, total_months)
                    )

risk_cluster[['n6_c4']]                  <- c4_prob
risk_cluster[['n6_c5']][1:24]            <- c5_prob_initial
risk_cluster[['n6_c5']][37:total_months] <- c5_prob_later
```

```{r create_inputs_calendar, echo=TRUE}
### Create the data to allow calculation of the calendar effect
dt_calendar <- data.table(calc_date   = c(as.Date("1900-01-01"), as.Date('2008-01-01')
                                         ,as.Date('2009-01-01'), as.Date('2012-01-01')
                                         ,as.Date('2013-01-01'))
                         ,lapse_prob = c(0.0000, 0.0010, 0.0015, 0.0010, 0.0000))

setkey(dt_calendar, calc_date)
```


```{r calculate_lapse_months, echo=TRUE}
### Use the above additive hazards to create the lapse function
### create_lapse_calculation_function is a function that returns a function
calculate_lapse_month <- create_lapse_calculation_function(risk_baseline
                                                          ,risk_gender
                                                          ,risk_smoker
                                                          ,risk_mortstat
                                                          ,risk_logpremape
                                                          ,risk_highpremape
                                                          ,risk_cluster
                                                          ,dt_calendar            = dt_calendar
                                                          ,min_monthly_lapse_prob = min_monthly_lapse_prob
                                                          ,premape_high           = premape_high
                                                          )

dt_policy[prod_type != 'protection'
         ,lapse_month := as.integer(round(rweibull(.N
                                                  ,nonprotection_weibull_shape
                                                  ,nonprotection_weibull_scale), 0))]

dt_policy[prod_type == 'protection'
         ,lapse_month := as.integer(calculate_lapse_month(.SD)), by = policy_id]

str(dt_policy)
```


## Use Lapse Month to Determine Lapses and Set policy_status

```{r determine_lapses, echo=TRUE}
### policy_lapsedate is the possibly-future date that the policy lapses
dt_policy[, policy_lapsedate := policy_startdate %m+% months(lapse_month)]


### First we look at policies where policy_enddate is prior to the snapshot date
dt_policy[policy_enddate <= data_date
         ,policy_status := ifelse(policy_lapsedate > policy_enddate, 'completed', 'lapsed')]

### Now we set the status for policies with policy_enddate after the snapshot date
dt_policy[policy_enddate > data_date
         ,policy_status := ifelse(policy_lapsedate < data_date, 'lapsed', 'inforce')]

### We set policy_statuschangedate according to policy_status
dt_policy[policy_status == 'inforce',   policy_statuschangedate := policy_startdate]
dt_policy[policy_status == 'lapsed',    policy_statuschangedate := policy_lapsedate]
dt_policy[policy_status == 'completed', policy_statuschangedate := policy_enddate]

dt_policy[, lapsed := (policy_status == 'lapsed')]


dt_policy %>%
    group_by(lapsed) %>%
    summarise(count = n())

dt_policy %>%
    group_by(prod_type, lapsed) %>%
    summarise(count = n()) %>%
    arrange(prod_type, lapsed)

```

```{r create_output_data, echo=TRUE}
dt_output <- dt_policy[, .(policy_id,countyname,edname,nuts3name,sa_id,cluster_id,prod_type
                           ,prem_type,prem_freq,prem_ape,prem_risk,policy_startdate,policy_enddate
                           ,policy_duration,mort_rating,sum_assured
                           ,dob_life1,gender_life1,smoker_life1,isjointlife,islifeonly
                           ,mortgage_status,policy_status,policy_statuschangedate,lapsed)];

setkey(dt_output, policy_id);


dt_output %>%
    filter(policy_statuschangedate != policy_startdate
          ,policy_statuschangedate != policy_enddate) %>%
    group_by(lapsed) %>%
    summarise(count = n())
```



# Output Data

We write out our data to the output directory using a variety of data formats.

```{r output_data, echo=TRUE}
write_csv    (dt_output, path = 'output/dt_policy_inoutforce.csv')
write_feather(dt_output, path = 'output/dt_policy_inoutforce.feather')

## Convert the data to JSON and output it
write(jsonlite::toJSON(dt_output), file = 'output/lifeins_policybook_inoutforce.json')

## Write the Data as an R Data File
saveRDS(dt_output, file = 'output/lifeins_policybook_inoutforce.rds', compress = 'xz')


## Write standard files
write_csv    (dt_output, path = 'output/lifebook_data.csv')
write_feather(dt_output, path = 'output/lifebook_data.feather')
```
